/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "WaveDAC8.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "UART.h"
#include "ADC_DelSig.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "DMA_dma.h"
#include "ISR_DMA.h"
#include "Pin_PB_aliases.h"
#include "Pin_PB.h"
#include "ISR_PB.h"
#include "Pin_RedLED_aliases.h"
#include "Pin_RedLED.h"
#include "Pin_YellowLED_aliases.h"
#include "Pin_YellowLED.h"
#include "Pin_GreenLED_aliases.h"
#include "Pin_GreenLED.h"
#include "ISR_UART.h"
#include "WaveDAC8_DacClk.h"
#include "WaveDAC8_Wave1_DMA_dma.h"
#include "WaveDAC8_Wave2_DMA_dma.h"
#include "WaveDAC8_VDAC8.h"
#include "UART_IntClock.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

